# Generated by Django 4.2.6 on 2023-10-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
