# Generated by Django 4.2.6 on 2023-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
