# Generated by Django 4.2.6 on 2023-10-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['module_order']},
        ),
    ]
