# Generated by Django 4.2.6 on 2023-11-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_module_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
