# Generated by Django 4.2.6 on 2023-11-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_unlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to='module_notes/'),
        ),
    ]
