# Generated by Django 4.2.6 on 2023-11-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_module_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
