# Generated by Django 4.2.6 on 2023-11-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_favouritecourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='duration',
        ),
    ]
