# Generated by Django 4.2.6 on 2023-11-19 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_module_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
