# Generated by Django 4.2.6 on 2023-11-21 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_module_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created_at']},
        ),
    ]
