# Generated by Django 4.2.6 on 2023-12-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
