# Generated by Django 4.2.6 on 2023-10-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='state',
        ),
    ]
