# Generated by Django 4.2.6 on 2023-10-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_instructorprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='state',
        ),
    ]
