# Generated by Django 4.2.6 on 2023-11-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
