# Generated by Django 4.2.6 on 2023-10-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_instructorprofile_country_instructorprofile_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
