# Generated by Django 4.2.6 on 2023-10-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='skill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
