# Generated by Django 4.2.6 on 2023-11-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_transcation_order_id_transcation_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcation',
            options={'ordering': ['-transaction_date']},
        ),
    ]
