# Generated by Django 4.2.6 on 2023-11-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_alter_transcation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='module_completion_status',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
