# Generated by Django 4.2.6 on 2023-11-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_enrolledcourse_module_completion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='module_completion_status',
        ),
    ]
