# Generated by Django 4.2.6 on 2023-11-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_instructorprofile_wallet'),
        ('course', '0011_alter_course_options'),
        ('enrollment', '0005_remove_enrolledcourse_module_completion_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('module', 'student')},
            },
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='module_progress',
            field=models.ManyToManyField(blank=True, to='enrollment.moduleprogress'),
        ),
    ]
