# Generated by Django 4.2.6 on 2023-11-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_moduleprogress_enrolledcourse_module_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleprogress',
            name='completed_at',
        ),
    ]
