# Generated by Django 4.2.6 on 2023-11-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0007_remove_moduleprogress_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='module_progress',
        ),
    ]
